### ISSUE TITLE
SecondaryAlwaysOn_Example.ps1 - can not create a cluster

### ISSUE THREAD

**Issue by makeitcloudy** [aultt/DSCSQLCompositeResources#1]
hi Troy.
I’m stuck with the Secondary alwaysOn – it is not installing the failover cluster manager on the second node. 
Just wondering should I keep the LCM in Busy state when the sql’s are gettng restarted, and wait until it finish it’s job, or should the configuration be rerun again, when sql nodes are restarted ? after it is throwing an information that: [Configuration will be continued after reboot]

When I rerun it, then I’m thrown with error that: 

> MSFT_xSQLServerMEmory failed to alter the server configuration memory for second SQL node

then

>  Get-ClusterGroup is not recognized as the name of cmdlet on second SQL node,

 then

> xWaitForAvailabilityGroupAG1 threw a non-terminating errors when running Test-TargetResource functionality, 

then

> check the spelling of your cluster node on primary sql

 (even though the DNS A exist in the domain), then

> [xCluster]AlwaysOnClust – threw a non-terminating error when running Test-TargetResource functionality 

and finally

> HADR is no enabled on primary SQL node..

will start troubleshooting this evening again, as I did previously for the two tier pki deployment…
any help would be appreciated.

**Comment by aultt** [comment]
IF you receive Configuration will be continued after reboot you should not need to rerun the configuration.  it will pick up where it left off.  If you want to check the status run Test-DscConfiguration.

**Comment by aultt** [comment]
@tansei where you able to resolve this or are you still having issues
